version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.3.2
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.5.3

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  execute-cfn:
    executor: aws-cli/default
    steps:
      # リポジトリからソースコードを取得
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy Cloudformation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/network.yml --stack-name lecture13-network-stack
            aws cloudformation deploy --template-file cloudformation/security.yml --stack-name lecture13-security-stack --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation deploy --template-file cloudformation/application.yml --stack-name lecture13-application-stack
            aws cloudformation deploy --template-file cloudformation/database.yml --stack-name lecture13-database-stack

  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - SHA256:aqr6t8pCA+QW0OsiGO1WMSM6W+YtT3SfaG5oOM1le7Y
      - ansible-playbook/install:
          version: 2.10.7
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - ansible-playbook/playbook:
          playbook: playbook.yml
          playbook-options: -i inventory.ini -vvv

workflows:
  lecture13-provisioning:
    jobs:
      - cfn-lint
      - execute-cfn:
          requires:
            - cfn-lint
      - execute-ansible:
          requires:
            - execute-cfn
