- name: check if nvm is installed
  shell: bash -lc "nvm -v"
  register: nvm_exists
  changed_when: false
  ignore_errors: true

- name: install nvm if not present
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.40.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: /home/ec2-user
    creates: /home/ec2-user/.nvm/nvm.sh
  when: nvm_exists is failed

- name: check if node.js is installed
  shell: bash -lc "node -v | grep "{{ node_version }}""
  register: node_exists
  changed_when: false
  ignore_errors: true

- name: install node.js if not present
  become: no
  shell: >
    . /home/ec2-user/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: /home/ec2-user
    creates: /home/ec2-user/.nvm/versions/{{ item }}
  loop:
    - "{{ node_version }}"
  when: node_exists.failed

- name: check if yarn is installed
  shell: bash -lc "yarn -v | grep "{{ yarn_version }}""
  register: yarn_exists
  changed_when: false
  ignore_errors: true

- name: install yarn globally if not present
  shell: bash -lc "npm install -g yarn@{{ yarn_version }}"
  when: yarn_exists.failed

- name: install yarn locally if not present
  shell: bash -lc "yarn install"
  args:
    chdir: "{{ app_dir }}"
  when: yarn_exists.failed
