- name: check if nginx1 is installed
  become: true
  shell: "amazon-linux-extras list"
  register: amazon_linux_extras_list
  changed_when: false

- name: enable to install nginx1
  become: true
  shell: "amazon-linux-extras enable nginx1"
  when: "'nginx1=latest' not in amazon_linux_extras_list.stdout"

- name: install nginx
  become: true
  yum:
    name: nginx

- name: set nginx.conf.j2 template
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    mode: "644"

- name: change owner /var/lib/nginx
  become: true
  file:
    path: /var/lib/nginx/
    state: directory
    owner: ec2-user
    group: ec2-user
    recurse: true

- name: restart nginx
  become: true
  systemd:
    name: nginx
    state: restarted

- name: restart puma
  become: true
  systemd:
    name: puma
    state: restarted
